version: 2

sources:
  - name: sap_adw
    schema: sap_adw
    description: Adventureworks postgres erp database source bases
    tables:
      - name: address
      - name: stateprovince
      - name: countryregion
      - name: creditcard
      - name: customer
      - name: person
      - name: product
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesreason
      - name: store
      - name: salesorderheadersalesreason